name: Build APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Mencegah timeout pada build panjang
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Versi spesifik yang stabil untuk Buildozer

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev \
          libtinfo5 cmake libffi-dev libssl-dev \
          libltdl-dev  # Menambahkan dependensi kritis yang sering kurang

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython virtualenv

    - name: Cache dependencies
      uses: actions/cache@v3
      id: buildozer-cache
      with:
        path: |
          ~/.buildozer
          ~/.local/share/python-for-android
          ./.buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-

    - name: Setup Buildozer
      run: |
        buildozer init  # Generate config jika belum ada
        buildozer android update  # Update dependensi android

    - name: Build APK
      run: |
        # Set environment variables untuk menghindari prompt
        export P4A_RELEASE_KEYSTORE=/dev/null
        export P4A_RELEASE_KEYSTORE_PASSWD=dummy
        export P4A_RELEASE_KEYALIAS_PASSWD=dummy
        
        buildozer -v android debug 2>&1 | tee build.log  # Simpan log
        
        # Perbaikan izin file hasil build
        find . -name "*.apk" -exec chmod 644 {} \;

    - name: Upload APK
      if: success() || failure()  # Tetap upload meski build gagal
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: bin/*.apk

    - name: Upload build log
      uses: actions/upload-artifact@v4
      with:
        name: build-log
        path: build.log
