name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.13.2
      uses: actions/setup-python@v5
      with:
        python-version: '3.13.2'
        check-latest: true
        
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            libltdl-dev \
            libffi-dev \
            libssl-dev \
            libxml2-dev \
            libxslt-dev \
            python3-dev \
            libiconv-dev
            
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython virtualenv
        pip install --no-binary pandas pandas
        
    - name: Configure Buildozer
      run: |
        if [ -f buildozer.spec ]; then
          echo "buildozer.spec found, using existing file"
          sed -i 's/flyer/plyer/g' buildozer.spec
          sed -i 's/android.archs =/android.arch =/g' buildozer.spec
        else
          buildozer init
          echo "Created new buildozer.spec"
        fi
        
    - name: Setup cache for Buildozer
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
          ~/.gradle/caches
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
          
    - name: Clean project
      run: |
        # Hapus folder build lokal (di proyek) dan folder bin
        rm -rf .buildozer bin

    - name: Build APK
      run: |
        export PATH=$PATH:$HOME/.local/bin
        export NDK_VERSION=25b
        export ANDROID_NDK_HOME=$HOME/android-ndk-r$NDK_VERSION
        
        buildozer -v android release
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: sigmaguru-apk
        path: bin/*.apk
        retention-days: 3
