# .github/workflows/build_apl.yml
name: Build Android APK

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the 'main' branch
  pull_request:
    branches:
      - main # Trigger the workflow on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to check out your code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specify the Python version you're using

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev libncurses5-dev libncursesw5-dev libffi-dev libssl-dev
        pip install --upgrade pip setuptools virtualenv

    - name: Install Buildozer
      run: pip install buildozer

    - name: Configure Buildozer (optional, if you need to modify buildozer.spec programmatically)
      # You can add steps here to modify buildozer.spec if needed.
      # For example, to set the app name or version from a variable:
      # run: |
      #   sed -i "s/^title = .*$/title = My SIGMA Guru App/" buildozer.spec
      #   sed -i "s/^version = .*$/version = 1.0.0/" buildozer.spec
      run: echo "Buildozer configuration complete." # Placeholder

    - name: Run Buildozer
      run: buildozer android debug # Builds a debug APK for Android

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk # Uploads all APK files generated by Buildozer
