name: Build Android APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libtinfo5 \
            libltdl-dev \
            libffi-dev \
            libssl-dev
            
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install buildozer cython virtualenv
        
    - name: Configure Buildozer
      run: |
        buildozer init
        # Replace with our spec file
        rm -f buildozer.spec
        cp YOUR_SPEC_FILE.spec buildozer.spec  # Replace with your spec filename
        
    - name: Set up Android NDK
      run: |
        echo "android.ndk_path = $HOME/.buildozer/android/platform/android-ndk-r25b" >> buildozer.spec
        
    - name: Build APK
      run: |
        export PATH=$PATH:~/.local/bin/
        buildozer -v android debug
        
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: sigmaguru-apk
        path: bin/*.apk
        retention-days: 3
